### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by wb12581** [Kutear/Fuck-Hard-Code#1]
Fuck-Hard-Code -input="{layout path}" -output="{layout output path}"这行添加在哪?
github上的代码怎么放在项目里 没看明白

**Comment by kutear** [comment]
@wb12581 
`Fuck-Hard-Code`是程序的名字，windows下对应`Fuck-Hard-Code.exe` 
input参数是指你的app/src/main/res/layout目录的全路径，
output是修改之后的`app/src/main/res/layout`的输出目录，
不直接修改原目录的原因是让用户可以使用一些工具对比修改前和修改后的内容，
确保正确之后可以使用output覆盖以前的input

**Comment by wb12581** [comment]
谢谢您耐心细致的解答,现在明白了
